---

- name: service apache reload
  service: name={{ apache_service }} state=reloaded
  become: yes

- name: service apache restart
  service: name={{ apache_service }} state=restarted
  become: yes

