---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: install php-fpm packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ php_fpm }}"
    - "{{ php_mysql }}"
