---
- include_vars: "{{ ansible_os_family }}.yml"

- name: install apache
  become: yes
  package: "name={{ apache_package_name }} state=latest"

- name: run apache
  become: yes
  service: "name={{apache_service_name}} state=started enabled=yes"
