---

- include_vars: "{{ ansible_os_family }}.yml"

- name: install apache
  become: yes
  package: "name={{ apache_package_name }} state=latest"

- name: "post-tasks; per distro fixes"
  include: "{{ ansible_os_family }}.yml"

- name: service apache start
  become: yes
  service: "name={{ apache_service_name }} state=started enabled=yes"


