---
- include_vars: "{{ ansible_os_family }}.yml"

- name: install apache
  become: yes
  package: "name={{ apache_package_name }} state=latest"

- name: run apache
  become: yes
  service: "name={{apache_service_name}} state=started enabled=yes"

# XXX Wouldn't it be nice to do this here.
# Initial steps to convert httpd to a debian-esque style configuration.
#- include: {{ ansible_os_family }}.yml
#  when: ansible_os_family == "RedHat"

