---

- include_vars: "{{ ansible_os_family }}.yml"

- name: install apache
  become: yes
  package: "name={{ item }} state=latest"
  with_items: "{{ apache_packages }}"

- name: "post-tasks; per distro fixes"
  include: "{{ ansible_os_family }}.yml"

- name: service apache start
  become: yes
  service: "name={{ apache_service }} state=started enabled=yes"


