---

# upstream apache configuration used by RedHat systems is a
# {flaming turd|steaming pile of shit} This is an attempt to clean it up
# in a somewhat debian-esque manner, and make it less sucky.

#- name: stop httpd
#  service: name=httpd state=stopped
#  become: yes

- name: check {{ apache_conf_dir }} directories
  file: path={{ dir }} state=directory owner=root group=root
  become: yes
  with_items:
    - "{{ apache_conf_dir }}/conf-available"
    - "{{ apache_conf_dir }}/conf-enabled"
    - "{{ apache_conf_dir }}/mods-available"
    - "{{ apache_conf_dir }}/mods-enabled"
    - "{{ apache_conf_dir }}/sites-available"
    - "{{ apache_conf_dir }}/sites-enabled"
  loop_control:
    loop_var: dir

- name: check /var/lock/httpd directory
  file: path=/var/lock/httpd state=directory owner=apache group=apache
  become: yes

- name: check /var/www directory
  file: path=/var/www state=directory owner=apache group=apache mode=2775
  become: yes

#
# File management
#

- name: super-clean-out conf.modules.d/00-base.conf
  script: split-00-base.conf.py removes={{ apache_conf_dir }}/conf.modules.d/00-base.conf
  become: yes

- name: copy files
  copy: "src={{ file.src }} dest={{ file.dest }}"
  become: yes
  with_items: "{{ files_to_copy }}"
  loop_control:
    loop_var: file

- name: stat files to move
  stat: path={{ file.src }}
  with_items: "{{ files_to_move }}"
  register: files
  loop_control:
    loop_var: file

- name: move files
  command: "mv {{ file.item.src }} {{ file.item.dest }}"
  when: file.stat.exists == True
  with_items: "{{ files.results }}"
  loop_control:
    loop_var: file

- name: remove files
  file: path={{ file }} state=absent
  with_items: "{{ files_to_remove }}"
  loop_control:
    loop_var: file

#
# Configuration
#

- name: update /etc/sysconfig/httpd
  lineinfile: dest=/etc/sysconfig/httpd regexp='^OPTIONS=*' line="OPTIONS=\"-f httpd.conf\"" insertafter='^#OPTIONS=*' state=present
  become: yes
  notify: service apache restart

- name: strip Listen from ssl.conf
  lineinfile: dest={{ apache_conf_dir }}/mods-available/ssl.conf line="Listen 443 https" state=absent
  become: yes

- name: force TLSv1.2 only
  lineinfile: dest={{ apache_conf_dir }}/mods-available/ssl.conf line="SSLProtocol TLSv1.2" state=present
  become: yes

- name: strip <VirtualHost> from ssl.conf
  replace:    dest={{ apache_conf_dir }}/mods-available/ssl.conf regexp='^<VirtualHost _default_:443>((?:.|\n)*?)</VirtualHost>\s+$' replace=''
  become: yes

- name: enable conf/mods
  file: src={{ file.src }} dest={{ file.dest }} state={{ file.state }}
  become: yes
  with_items: "{{ files_to_symlink }}"
  loop_control:
    loop_var: file

# Residual

#- name: remove residual files and symlinks
#  script: roles/apache/files/residual.py removes=/etc/httpd/conf.d/README
#  become: yes

#- name: "remove if empty: /etc/httpd/conf"
#- name: "remove if empty: /etc/httpd/conf.d"
#- name: "remove if empty: /etc/httpd/conf.modules.d"

