---

- name: Tune Fedora workstation
  hosts: localhost

  vars:
    monitor_programs:
    - htop
    - iftop
    - iotop
    - sysstat
    disk_utils:
    - exfat-utils
    - fuse-exfat
    - fuse-sshfs
    devel_utils:
    - autoconf
    - automake
    - gcc
    - gcc-c++
    - git
    - jq
    - libtool
    - redhat-rpm-config
    media:
    - gstreamer1-plugins-bad-free
    - gstreamer1-plugins-bad-freeworld
    - gstreamer1-plugins-good
    - gstreamer1-plugins-ugly
    - mplayer
    - mpv
    - youtube-dl

  pre_tasks:
  - ansible.builtin.pip:
      name:
      - psutil
      extra_args: --user

  - name: fix sudoers
    ansible.builtin.replace:
      path: /etc/sudoers
      regexp: "{{ item.regexp }}"
      replace: "{{ item.replace }}"
    loop_control:
      label: "{{ item.label }}"
    with_items:
    - regexp: '^#?\s?+(?P<line>.*NOPASSWD.*)$'
      replace: '\g<line>'
      label: "enable with NOPASSWD"
    - regexp: '^#?\s?+(?P<line>%wheel(?:(?!NOPASSWD).)*)$'
      replace: '# \g<line>'
      label: "disable without NOPASSWD"
    become: true

  - name: install rpmfusion repo
    ansible.builtin.dnf:
      name: "{{ item.uri }}"
    loop_control:
      label: "{{ item.label }}"
    with_items:
    - uri: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      label: free
    - uri: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      label: non-free
    ignore_errors: true
    become: true

  - name: install packages
    ansible.builtin.dnf:
      name: "{{ packages | flatten }}"
      state: latest
    vars:
      packages:
      - gnome-tweaks
      - nmap
      - renameutils
      - vim-enhanced
      - "{{ monitor_programs }}"
      - "{{ disk_utils }}"
      - "{{ devel_utils }}"
      - "{{ media }}"
    become: true

  - name: remove packages
    ansible.builtin.dnf:
      name: "{{ packages | flatten }}"
      state: absent
    vars:
      packages:
      - libreoffice-calc
      - libreoffice-draw
      - libreoffice-impress
      - net-tools
    become: true

  tasks:
  - name: setup ssh
    systemd:
      name: sshd
      enabled: true
      state: started
    become: true

  - name: enable fractional scaling in gnome
    community.general.dconf:
      key: /org/gnome/mutter/experimental-features
      value: "['scale-monitor-framebuffer']"
