- name: deploy linodes
  hosts: localhost

  vars:
    nodes:
      - label: peggy
        type: g6-nanode-1
        region: us-east
        image: linode/ubuntu18.04
      - label: regan
        type: g6-nanode-1
        region: eu-west
        image: linode/centos7
      - label: sofia
        type: g6-nanode-1
        region: eu-central
        image: linode/debian9
      - label: tracy
        type: g6-nanode-1
        region: us-central
        image: linode/ubuntu16.04lts

# "us-central":   Dallas,  TX
# "us-east":      Newark,  NJ
# "us-southeast": Atlanta, GA
# "us-west":      Fremont, CA

  pre_tasks:
    - name: include secrets (linode_{auth_token,root_pass})
      include_vars: "secrets.yml"

  tasks:
#    - name: query regions
#      uri:
#        url: https://api.linode.com/v4/regions
#        headers:
#          Authorization: "Bearer {{ linode_auth_token }}"
#      register: _lr
#
#    - set_fact:
#        _linode_regions: "{{ _linode_regions | default({}) | combine({ item.id : item.country }) }}"
#      with_items: "{{ _lr.json.data }}"
#
#    - name: query images
#      uri:
#        url: https://api.linode.com/v4/images
#        headers:
#          Authorization: "Bearer {{ linode_auth_token }}"
#      register: _li
#
#    - set_fact:
#        _linode_images: "{{ _linode_images | default({}) | combine({ item.id : item.label }) }}"
#      with_items: "{{ _li.json.data }}"
#
#    - name: query types
#      uri:
#        url: https://api.linode.com/v4/linode/types
#        headers:
#          Authorization: "Bearer {{ linode_auth_token }}"
#      register: _lt
#
#    - set_fact:
#        _linode_types: "{{ _linode_types | default({}) | combine({ item.id : item.label }) }}"
#      with_items: "{{ _lt.json.data }}"

    - name: query linodes
      uri:
        url: https://api.linode.com/v4/linode/instances
        headers:
          Authorization: "Bearer {{ linode_auth_token }}"
        return_content: true
      register: _ls

    - set_fact:
        _linodes: "{{ _linodes | default({}) }}"

    - set_fact:
        _linodes: "{{ _linodes | combine({ item.label :  { 'json' : { 'label': item.label, 'ipv4': item.ipv4, 'image': item.image }, 'label': item.label } }) }}"
      with_items: "{{ _ls.json.data }}"

###

    - name: create linode
      uri:
        method: POST
        url: https://api.linode.com/v4/linode/instances
        headers:
          Authorization: "Bearer {{ linode_auth_token }}"
        body_format: json
        body:
          type: "{{ item.type }}"
          region: "{{ item.region }}"
          authorized_keys:
            - "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
          image: "{{ item.image }}"
          root_pass: "{{ linode_root_pass }}"
          label: "{{ item.label }}"
        return_content: true
      with_items: "{{ nodes }}"
      when: item.label not in _linodes
      register: _linodes_created

    - name: create inventory/linodes file
      lineinfile:
        path: inventory/linodes
        create: true
        line: "[linodes]"

    - name: populate inventory/linodes file
      lineinfile:
        path: inventory/linodes
        regexp: "^{{ item.json.label }} *"
        line: "{{ item.json.label }} ansible_host={{ item.json.ipv4[0] }}{% if (item.json.image is search('ubuntu')) %} ansible_python_interpreter=/usr/bin/python3{% endif %}"
      with_items:
        - "{{ _linodes_created.results }}"
        - "{{ _linodes | json_query('*') }}"
      when: item.json is defined
