---

- name: Wordpressify Linodes
  hosts: linodes

  pre_tasks:
    - name: install EPEL and IUS on CentOS 7
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - epel-release
        - https://centos7.iuscommunity.org/ius-release.rpm
      when:
        - ansible_distribution == 'CentOS'
        - ansible_distribution_major_version|int == 7

    - name: install python2-dnf on Fedora 22+
      command: dnf install python2-dnf -y
      warn: false
      when: ansible_distribution == 'Fedora' and ansible_distribution_major_version|int >= 22

#    - name: install python-httplib2 for ansible uri functions
#      package:
#        name: python-httplib2
#        state: latest

#    - name: install python selinux packages
#      package:
#        name: "{{ item }}"
#        state: latest
#      with_items:
#        - "libselinux-python"
#        - "libsemanage-python"
#      when: ansible_os_family == 'RedHat'

#    - name: fix sudoers
#      replace: dest=/etc/sudoers regexp={{ sudoers.regexp }} replace={{ sudoers.line }}
#      become: yes
#      when: ansible_os_family == sudoers.os
#      with_items:
#        - { os: "Debian", regexp: '^%sudo\s+((?!NOPASSWD).)*$',  line: "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" }
#        - { os: "RedHat", regexp: '^%wheel\s+((?!NOPASSWD).)*$', line: "%wheel ALL=(ALL) NOPASSWD: ALL"    }
#      loop_control:
#        loop_var: sudoers

  roles:
    - apache
#    - common
#    - glusterfs
#    - mariadb
#    - php
#    - phpmyadmin
#    - pdnsmanager
#    - powerdns
#    - ssl-cert
#    - wordpress

#  tasks:
#  - name: "wordpress : glue"
#    include: "roles/wordpress/tasks/glue.yml"
#
#  - name: "wordpress : gluster"
#    include: "roles/wordpress/tasks/gluster.yml"

#  - name: btrfs subvol
#    include: btrfs-subvol.yml
#    include: btrfs-subvol.yml mountpoint=/var/lib/mail
