---

php: "php56u"
php_mysql: "php56u-mysqlnd"
php_apache_mod: "php"

files_to_move:
  - { src: "{{ apache_conf_dir }}/conf.d/php.conf",            dest: "{{ apache_conf_dir }}/mods-available/php.conf" }
  - { src: "{{ apache_conf_dir }}/conf.modules.d/10-php.conf", dest: "{{ apache_conf_dir }}/mods-available/php.load" }

