---

- name: "wordpress : glue : include_vars"
  include_vars: "roles/apache/vars/{{ ansible_os_family }}.yml"

#
# Cleanup.
#

- name: "wordpress : glue : remove sites-*/000-default.conf"
  file: path={{ item }} state=absent
  become: yes
  with_items:
    - "{{ apache_config_path }}/sites-available/000-default.conf"
    - "{{ apache_config_path }}/sites-enabled/000-default.conf"

#
# Glue.
#

- name: "wordpress : glue : copy default-ssl.conf to sites-available"
  template: src="roles/wordpress/templates/apache-default-ssl-{{ ansible_os_family }}.conf.j2" dest="{{ apache_config_path }}/sites-available/default-ssl.conf"
  become: yes

- name: "wordpress : glue : create sites-enabled symlink for default-ssl.conf"
  file: src=../sites-available/default-ssl.conf dest={{ apache_config_path }}/sites-enabled/default-ssl.conf state=link
  become: yes
#  notify: service apache reload

