---

- include_vars: "{{ ansible_os_family }}.yml"

- name: install mariadb packages
  package: "name={{ item }} state=latest"
  become: yes
  with_items:
    - "{{ mariadb_server }}"
    - "{{ mysql_python }}"

- name: service mariadb-server start
  service: "name={{ mariadb_service }} state=started enabled=yes"
  become: yes

