---

- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: "install mariadb packages"
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ mariadb_server }}"
    - "{{ mysql_python }}"

#- name: "check if my.cnf is a symlink"
#  stat: path={{ mariadb_cnf }}
#  register: check
#
#- name: "remove said my.cnf symlink"
#  file: path={{ mariadb_cnf }} state=absent
#  become: yes
#  when: check.stat.islnk == true
#
#- name: remove crud
#  file: path={{ item }} state=absent
#  become: yes
#  with_items:
#    - "{{ mariadb_crud }}"
#    - "{{ mariadb_cnf_dir }}/my.cnf.fallback"
#    - "{{ mariadb_inc_dir }}/mysql.cnf"
#    - "{{ mariadb_inc_dir }}/mysqldump.cnf"
#
#- name: "copy sane my.cnf"
#  template: "src=my.cnf.j2 dest={{ mariadb_cnf }}"
#  become: yes
#  register: config
#
## because CentOS has unix_socket under /var/run/mariadb/mysql.sock
#- name: copy /root/.my.cnf
#  template: src=root.my.cnf.j2 dest=/root/.my.cnf
#  become: yes
#  when: ansible_os_family == 'RedHat'
#
#- name: "service mariadb-server restart"
#  service: "name={{ mariadb_service }} state=restarted"
#  become: yes
#  when: config.changed == true
#
#- name: "service mariadb-server start"
#  service: "name={{ mariadb_service }} state=started enabled=yes"
#  become: yes

