---

- include_vars: "{{ ansible_os_family }}.yml"

- name: install mysql packages
  package: "name={{ item }} state=latest"
  become: yes
  with_items:
    - "{{ mysql_server }}"
    - "{{ mysql_python }}"

- name: service mysql-server start
  service: "name={{ mysql_service }} state=started enabled=yes"
  become: yes

