---

php_fpm:
  version: 7.0
  packages:
    - php7.0-fpm
  service: php7.0-fpm
  systemd: /lib/systemd/system
  bin: /usr/sbin/php-fpm7.0
  conf_file: /etc/php/7.0/fpm/php-fpm.conf
  pool_path: /etc/php/7.0/fpm/pool.d
  run_path: /run/php
  state_path: /var/lib/php-fpm
  log_path: /var/log
  error_log: php7.0-fpm.log
  status_path: /usr/share/php/7.0
  pid: php7.0-fpm.pid
  default_pool:
    name: www
    user: www-data
    group: www-data
    listen:
      socket: php7.0-fpm.sock
      owner: www-data
      group: www-data
      mode: '0660'
    env:
    php_admin_value:
      error_log: fpm-php.www.log
      memory_limit: 32M
    php_value:
    pm:
      max_children: 5
      start_servers: 2
      min_spare_servers: 1
      max_spare_servers: 3
    session:
      save_path: session
    soap:

php_mysql: php7.0-mysql
