---

# "pre-task": add gluster 3.7 repository based on distribution
- include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

# XXX BUG: with_first_found looks first for files in tasks/.
# https://github.com/ansible/ansible/pull/16630 will fix this.
# Luckily I can get away without using it.
- include_vars: "{{ ansible_os_family }}.yml"

- name: install gluster packages
  package: "name={{ item }} state=latest"
  become: yes
  with_items:
    - "{{ glusterfs_client }}"
    - "{{ glusterfs_server }}"

- name: start glusterd service
  service: "name={{ glusterfs_service }} state=started enabled=yes"
  become: yes

- name: update firewall
  firewalld: service=glusterfs state=enabled permanent=yes immediate=yes
  become: yes
  when: ansible_os_family == 'RedHat'
