---

- include: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Debian'

- include_vars: "{{ ansible_os_family }}.yml"

- name: install python-httplib2 for ansible uri functions.
  package: name={{ httplib2_package_name }} state=latest
  become: yes

- name: install fail2ban
  package: name={{ fail2ban_package_name }} state=latest
  become: yes

- name: tweak fail2ban recidive enabled
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=recidive option=enabled value=true
  notify: restart fail2ban service
  become: yes

- name: tweak fail2ban recidive bantime
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=recidive option=bantime value=-1
  notify: restart fail2ban service
  become: yes

- name: tweak fail2ban recidive findtime
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=recidive option=findtime value=86400
  notify: restart fail2ban service
  become: yes

- name: tweak fail2ban recidive maxretry
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=recidive option=maxretry value=3
  notify: restart fail2ban service
  become: yes

- name: tweak fail2ban sshd enabled
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=sshd option=enabled value=true
  notify: restart fail2ban service
  become: yes

- name: tweak fail2ban sshd findtime
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=sshd option=findtime value=3600
  notify: restart fail2ban service
  become: yes

- name: tweak fail2ban sshd maxretry
  ini_file: dest=/etc/fail2ban/jail.d/local.conf section=sshd option=maxretry value=3
  notify: restart fail2ban service
  become: yes

- name: start fail2ban service
  service: "name={{ fail2ban_service_name }} state=started enabled=yes"
  become: yes
