---

- name: "Do pre-task stuff per distribution"
  include: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == 'Debian'

- name: install sorely missed packages
  package: name={{ item }} state=latest
  become: yes
  with_items:
    - "fail2ban"
    - "vim"
    - "wget"

- name: tweak fail2ban
  include: fail2ban.yml

- name: start fail2ban service
  service: name=fail2ban state=started enabled=yes
  become: yes

