---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version | int }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: install php
  become: yes
  package: "name={{php_package_name}} state=latest"

- name: install php-mysql
  become: yes
  package: "name={{php_mysql_package_name}} state=latest"
